let currentSite = window.location.hostname.replace(/^www\./, '');

let configCache = null;
let timeInterval = null;
let enforceInterval = null;
let filterInterval = null;
let filterObserver = null;

let trackedVideoUrls = new Set();
let focusKeywords = { music: [], study: [], custom: [] };

// ====================== KEYWORD SYSTEM ======================

function loadKeywords(callback) {
  chrome.storage.local.get(['focusKeywords'], (result) => {
    let kw = result.focusKeywords || {
      music: ["lofi", "lo-fi", "music", "música", "chill", "radio", "soundtrack", "ost", "mix", "playlist", "beat", "beats", "álbum", "album", "lyrics", "cover"],
      study: ["sql", "mysql", "postgresql", "banco de dados", "tj ce", "tjce", "fcc", "concurso", "estudo", "aula", "curso", "tutorial", "resolução", "prova", "questões"],
      custom: []
    };
    focusKeywords.music = kw.music || [];
    focusKeywords.study = kw.study || [];
    focusKeywords.custom = kw.custom || [];
    if (callback) callback();
  });
}

function matchesKeywordsCategory(text) {
  if (!text) return null;
  let t = text.toLowerCase();
  for (let kw of focusKeywords.study) { if (t.includes(kw)) return "study"; }
  for (let kw of focusKeywords.music) { if (t.includes(kw)) return "music"; }
  for (let kw of focusKeywords.custom) { if (t.includes(kw)) return "custom"; }
  return null;
}

function matchesKeywords(text) {
  return matchesKeywordsCategory(text) !== null;
}

// ====================== SMART MUSIC DETECTION ======================
// Only uses RELIABLE signals: title, channel name, YouTube category metadata.
// IGNORES: comments, description body, background music credits.

function getPrimaryVideoText() {
  let texts = [];

  // 1. Page <title> — most reliable signal
  let titleTag = document.querySelector('title');
  if (titleTag) texts.push(titleTag.innerText);

  // 2. Player title (the big h1 above the video)
  let playerTitles = document.querySelectorAll(
    'h1.ytd-watch-metadata yt-formatted-string, ' +
    '#title h1 yt-formatted-string, ' +
    'h1.ytd-video-primary-info-renderer, ' +
    '#info-contents h1, ' +
    'ytd-watch-metadata #title'
  );
  playerTitles.forEach(el => { if (el.innerText) texts.push(el.innerText); });

  // 3. Channel name
  let channels = document.querySelectorAll(
    '#channel-name a, ytd-channel-name a, #owner-name a, #upload-info #channel-name'
  );
  channels.forEach(el => { if (el.innerText) texts.push(el.innerText); });

  // 4. Hashtags (those above the title like #lofi #study)
  let hashtags = document.querySelectorAll('a[href*="/hashtag/"]');
  hashtags.forEach(el => { if (el.innerText) texts.push(el.innerText); });

  return texts;
}

function getYouTubeCategory() {
  // Extract the official YouTube video category from embedded JSON
  let scripts = document.getElementsByTagName('script');
  for (let s of scripts) {
    let html = s.innerHTML;
    if (html.length > 500 && (html.includes('ytInitialPlayerResponse') || html.includes('ytInitialData'))) {
      // Check official category
      let catMatch = html.match(/"category"\s*:\s*"([^"]+)"/);
      if (catMatch) return catMatch[1];
    }
  }
  // Fallback: meta tag
  let genreMeta = document.querySelector('meta[itemprop="genre"]');
  if (genreMeta) return genreMeta.content;
  return null;
}

function isWhitelistedContent() {
  if (!currentSite.includes("youtube.com")) return null;
  if (window.location.hostname === "music.youtube.com") return "music";
  if (window.location.pathname !== "/watch") return null;

  // Step 1: Check title + channel + hashtags against keyword lists
  let primaryTexts = getPrimaryVideoText();
  for (let text of primaryTexts) {
    let category = matchesKeywordsCategory(text);
    if (category) return category;
  }

  // Step 2: YouTube's own category metadata (very reliable)
  let ytCategory = getYouTubeCategory();
  if (ytCategory) {
    let catLower = ytCategory.toLowerCase();
    if (catLower === "music" || catLower === "música") return "music";
    if (catLower === "education" || catLower === "educação" || catLower === "science & technology") return "study";
  }

  // Step 3: Auto-generated topic channels (always music)
  let allText = primaryTexts.join(' ');
  if (allText.includes("Auto-generated by YouTube")) return "music";

  // Step 4: Channel name patterns
  let channelTexts = document.querySelectorAll('#channel-name a, ytd-channel-name a');
  for (let ch of channelTexts) {
    let c = (ch.innerText || '').toLowerCase();
    if (c.includes("topic") || c.includes("vevo") || c.includes("records")) return "music";
  }

  // Step 5: Session memory from home page
  let currentVid = new URLSearchParams(window.location.search).get("v");
  if (currentVid) {
    try {
      let stored = sessionStorage.getItem('fg_focus_' + currentVid);
      if (stored) return stored;
    } catch(e) {}
  }

  return null;
}

// ====================== THUMBNAIL DETECTION (Home/Search) ======================

function isMusicThumbnail(container) {
  let timeOverlays = container.querySelectorAll('ytd-thumbnail-overlay-time-status-renderer');
  for (let ov of timeOverlays) {
    let attrStyle = ov.getAttribute('overlay-style');
    if (attrStyle && attrStyle.toUpperCase() === 'MUSIC') return true;
    try {
      if (ov.overlayStyle === 'MUSIC') return true;
      if (ov.data && ov.data.style === 'MUSIC') return true;
    } catch(e) {}
    let classes = ov.className || '';
    if (classes.includes('MUSIC')) return true;
  }

  let ariaEls = container.querySelectorAll('[aria-label]');
  for (let el of ariaEls) {
    let label = (el.getAttribute('aria-label') || '').toLowerCase();
    if (label.includes('music') || label.includes('música')) return true;
  }

  return false;
}

function isThumbnailAllowed(container, title) {
  let category = matchesKeywordsCategory(title);
  let isAllowed = !!category;

  if (!isAllowed && isMusicThumbnail(container)) {
    isAllowed = true;
    category = "music";
  }

  if (isAllowed && category) {
    let link = container.querySelector('a#thumbnail, a#video-title-link');
    if (link && link.href) {
      try {
        let url = new URL(link.href, window.location.origin);
        let vid = url.searchParams.get("v");
        if (vid) sessionStorage.setItem('fg_focus_' + vid, category);
      } catch(e) {}
    }
  }

  return isAllowed;
}

// ====================== INIT ======================

function init() {
  if (!currentSite) return;

  if (!document.getElementById("fg-style")) {
    let style = document.createElement("link");
    style.id = "fg-style";
    style.rel = "stylesheet";
    style.href = chrome.runtime.getURL("content.css");
    document.head.appendChild(style);
  }

  loadKeywords(() => {
    chrome.runtime.sendMessage({ action: 'GET_STATE' }, (response) => {
      if (response && response.focusConfig) {
        configCache = response.focusConfig;
        if (!configCache.targets[currentSite]) return;

        let t = configCache.targets[currentSite];
        let limitReached = t.current >= t.limit;
        if (configCache.mode === 'moderate' && configCache.globalLimitMod) {
          limitReached = (configCache.globalCurrent || 0) >= configCache.globalLimitTime;
        }

        if (limitReached) {
          startStrictEnforcer();
          return;
        }

        if (configCache.mode === 'moderate') {
          startTimeTracking();
        } else if (configCache.mode === 'extreme') {
          startExtremeTracking();
        }
      }
    });
  });
}

// ====================== TIME TRACKING ======================

function startTimeTracking() {
  timeInterval = setInterval(() => {
    if (document.hidden) return;

    if (currentSite.includes("youtube.com")) {
      if (window.location.pathname !== "/watch") return;
      if (!isMediaPlaying()) return;
      let category = isWhitelistedContent();
      if (category === "study") {
        chrome.runtime.sendMessage({ action: 'ADD_REWARD_TIME', site: currentSite });
        return;
      }
      if (category) return; // music/custom — don't count time at all
    }

    chrome.runtime.sendMessage({ action: 'ADD_TIME', site: currentSite });
  }, 1000);
}

function isMediaPlaying() {
  let mediaElements = document.querySelectorAll('video, audio');
  for (let m of mediaElements) {
    if (!m.paused && !m.ended && m.readyState > 2) return true;
  }
  return false;
}

function startExtremeTracking() {
  if (currentSite.includes("youtube.com")) {
    setInterval(() => {
      if (window.location.pathname === "/watch" && !document.hidden) {
        let category = isWhitelistedContent();
        if (category === "study" && isMediaPlaying()) {
          chrome.runtime.sendMessage({ action: 'ADD_REWARD_TIME', site: currentSite });
          return;
        }
        if (category) return; // whitelisted, don't count
        let videoId = new URLSearchParams(window.location.search).get("v");
        if (videoId && !trackedVideoUrls.has(videoId)) {
          trackedVideoUrls.add(videoId);
          chrome.runtime.sendMessage({ action: 'ADD_ITEM', site: currentSite });
        }
      }
    }, 2000);
  }
  else if (currentSite.includes("twitter.com") || currentSite.includes("x.com")) {
    const observer = new IntersectionObserver((entries) => {
      entries.forEach(entry => {
        if (entry.isIntersecting && !entry.target.dataset.fgTracked) {
          entry.target.dataset.fgTracked = "true";
          chrome.runtime.sendMessage({ action: 'ADD_ITEM', site: currentSite });
        }
      });
    }, { threshold: 0.5 });
    setInterval(() => {
      document.querySelectorAll('article[data-testid="tweet"]:not([data-fg-tracked])').forEach(el => observer.observe(el));
    }, 2000);
  }
  else if (currentSite.includes("instagram.com")) {
    const observer = new IntersectionObserver((entries) => {
      entries.forEach(entry => {
        if (entry.isIntersecting && !entry.target.dataset.fgTracked) {
          entry.target.dataset.fgTracked = "true";
          chrome.runtime.sendMessage({ action: 'ADD_ITEM', site: currentSite });
        }
      });
    }, { threshold: 0.5 });
    setInterval(() => {
      document.querySelectorAll('article:not([data-fg-tracked])').forEach(el => observer.observe(el));
    }, 2000);
  }
}

// ====================== BLOCKING ======================

function executeBlock() {
  if (currentSite.includes("youtube.com") && isWhitelistedContent()) {
    removeBlock();
    return;
  }

  document.querySelectorAll('video, audio').forEach(m => {
    if (!m.paused) m.dataset.fgWasPlaying = "true";
    m.pause();
    m.muted = true;
    m.volume = 0;
  });

  if (document.getElementById("fg-block-screen")) return;

  let blockUI = document.createElement("div");
  blockUI.id = "fg-block-screen";
  blockUI.className = "focusguard-blocked";
  blockUI.innerHTML = `
    <h1>Tempo Esgotado!</h1>
    <p>Você atingiu seu limite para o ${currentSite}. Volte ao trabalho!</p>
  `;
  document.body.appendChild(blockUI);
  document.body.style.overflow = "hidden";
}

function removeBlock() {
  let blockUI = document.getElementById("fg-block-screen");
  if (blockUI) {
    blockUI.remove();
    document.body.style.overflow = "";
    document.querySelectorAll('video, audio').forEach(m => {
      m.muted = false;
      if (m.dataset.fgWasPlaying === "true") {
        m.play().catch(() => {});
        delete m.dataset.fgWasPlaying;
      }
    });
  }
}

// ====================== HOME/SEARCH FILTERING ======================

function getContainerTitle(container) {
  let titleEl = container.querySelector('#video-title, #video-title-link, a#video-title-link yt-formatted-string');
  let title = '';
  if (titleEl) title = titleEl.innerText || titleEl.textContent || titleEl.getAttribute('title') || titleEl.getAttribute('aria-label') || '';
  if (!title) {
    let thumbLink = container.querySelector('a#thumbnail, a[href*="/watch"]');
    if (thumbLink) title = thumbLink.getAttribute('title') || thumbLink.getAttribute('aria-label') || '';
  }
  return title;
}

function hideDistractingVideos() {
  if (!currentSite.includes("youtube.com")) return;

  document.querySelectorAll('ytd-rich-item-renderer, ytd-video-renderer, ytd-grid-video-renderer, ytd-reel-item-renderer').forEach(container => {
    let title = getContainerTitle(container);
    if (!title) return;
    if (isThumbnailAllowed(container, title)) {
      container.style.removeProperty('display');
    } else {
      container.style.setProperty('display', 'none', 'important');
    }
  });

  document.querySelectorAll('ytd-compact-video-renderer, ytd-compact-radio-renderer').forEach(item => {
    let titleEl = item.querySelector('#video-title, .title, span#video-title');
    let title = titleEl ? (titleEl.innerText || titleEl.textContent || titleEl.getAttribute('title') || '') : '';
    if (!title) return;
    if (isThumbnailAllowed(item, title)) {
      item.style.removeProperty('display');
    } else {
      item.style.setProperty('display', 'none', 'important');
    }
  });

  document.querySelectorAll('ytd-rich-section-renderer').forEach(shelf => {
    let shelfTitle = shelf.querySelector('#title-text');
    let st = shelfTitle ? (shelfTitle.innerText || '') : '';
    if (matchesKeywords(st)) return;
    let items = shelf.querySelectorAll('ytd-rich-item-renderer, ytd-reel-item-renderer');
    let anyVisible = false;
    items.forEach(item => { if (item.style.display !== 'none') anyVisible = true; });
    if (!anyVisible) shelf.style.setProperty('display', 'none', 'important');
  });
}

function startFilterLoop() {
  hideDistractingVideos();
  if (filterInterval) clearInterval(filterInterval);
  filterInterval = setInterval(hideDistractingVideos, 800);
  if (!filterObserver) {
    let targetNode = document.querySelector('ytd-app') || document.body;
    filterObserver = new MutationObserver(() => hideDistractingVideos());
    filterObserver.observe(targetNode, { childList: true, subtree: true });
  }
}

// ====================== STRICT ENFORCER ======================

let blockGraceCounter = 0;
let lastEnforcerUrl = "";
let lastRewardTimestamp = 0;

function startStrictEnforcer() {
  if (timeInterval) clearInterval(timeInterval);
  let shouldFilter = configCache && configCache.hideDistractions !== false;

  enforceInterval = setInterval(() => {
    if (currentSite.includes("youtube.com")) {
      if (window.location.pathname === "/watch" || window.location.pathname.startsWith("/shorts/")) {
        if (window.location.href !== lastEnforcerUrl) {
          lastEnforcerUrl = window.location.href;
          blockGraceCounter = 0;
        }

        let category = isWhitelistedContent();
        if (category) {
          blockGraceCounter = 0;
          removeBlock();
          // Study content earns reward time — throttled to max once per second
          let now = Date.now();
          if (category === "study" && !document.hidden && isMediaPlaying() && now - lastRewardTimestamp >= 1000) {
            lastRewardTimestamp = now;
            chrome.runtime.sendMessage({ action: 'ADD_REWARD_TIME', site: currentSite });
          }
        } else {
          blockGraceCounter++;
          let vidEl = document.querySelector('video');
          if (vidEl && !vidEl.paused && blockGraceCounter <= 2) {
            vidEl.dataset.fgWasPlaying = "true";
            vidEl.pause();
          }
          if (blockGraceCounter > 2) executeBlock();
        }
      } else {
        blockGraceCounter = 0;
        removeBlock();
        if (shouldFilter) hideDistractingVideos();
      }
    } else {
      executeBlock();
    }
  }, 500);

  if (currentSite.includes("youtube.com") && shouldFilter) startFilterLoop();
}

// ====================== NOTIFICATIONS ======================

function playNotificationSound() {
  if (configCache && configCache.muteNotifications) return;
  try {
    let audioCtx = new (window.AudioContext || window.webkitAudioContext)();
    let osc1 = audioCtx.createOscillator();
    let gain1 = audioCtx.createGain();
    osc1.type = 'sine';
    osc1.frequency.setValueAtTime(880, audioCtx.currentTime);
    gain1.gain.setValueAtTime(0.08, audioCtx.currentTime);
    gain1.gain.exponentialRampToValueAtTime(0.001, audioCtx.currentTime + 0.4);
    osc1.connect(gain1); gain1.connect(audioCtx.destination);
    osc1.start(audioCtx.currentTime); osc1.stop(audioCtx.currentTime + 0.4);

    let osc2 = audioCtx.createOscillator();
    let gain2 = audioCtx.createGain();
    osc2.type = 'sine';
    osc2.frequency.setValueAtTime(1100, audioCtx.currentTime + 0.15);
    gain2.gain.setValueAtTime(0.06, audioCtx.currentTime + 0.15);
    gain2.gain.exponentialRampToValueAtTime(0.001, audioCtx.currentTime + 0.55);
    osc2.connect(gain2); gain2.connect(audioCtx.destination);
    osc2.start(audioCtx.currentTime + 0.15); osc2.stop(audioCtx.currentTime + 0.55);
  } catch(e) {}
}

function showWarning(msg) {
  document.querySelectorAll('.focusguard-warning').forEach(el => el.remove());
  playNotificationSound();
  let overlay = document.createElement('div');
  overlay.className = 'focusguard-warning';
  overlay.innerHTML = `
    <div class="fg-warn-icon">⚠️</div>
    <div class="fg-warn-title">FocusGuard</div>
    <div class="fg-warn-msg">${msg}</div>
    <div class="fg-warn-close">✕</div>
  `;
  document.body.appendChild(overlay);
  overlay.querySelector('.fg-warn-close').addEventListener('click', () => {
    overlay.style.animation = 'slideOutFG 0.4s ease forwards';
    setTimeout(() => overlay.remove(), 400);
  });
  setTimeout(() => {
    if (overlay.parentNode) {
      overlay.style.animation = 'slideOutFG 0.4s ease forwards';
      setTimeout(() => overlay.remove(), 400);
    }
  }, 8000);
}

// ====================== MESSAGE HANDLER ======================

chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  if (request.action === 'BLOCK_PAGE') {
    startStrictEnforcer();
  } else if (request.action === 'SHOW_WARNING') {
    showWarning(request.message);
  } else if (request.action === 'SHOW_REWARD') {
    showWarning(`🏆 Parabéns! Você completou ${request.minutes} min de estudo. Todos os timers foram resetados!`);
  } else if (request.action === 'UNBLOCK') {
    window.location.reload();
  } else if (request.action === 'UPDATE_CONFIG') {
    configCache = request.config;
  } else if (request.action === 'UPDATE_KEYWORDS') {
    let kw = request.keywords;
    focusKeywords.music = kw.music || [];
    focusKeywords.study = kw.study || [];
    focusKeywords.custom = kw.custom || [];
  }
});

init();
